
SELECT * FROM dbo.PERSONA;


ALTER TABLE Persona
DROP CONSTRAINT DF__PERSONA__IsActiv__7E8CC4B1;


ALTER TABLE Persona DROP COLUMN IsActive;

SELECT * FROM dbo.ROL;

SELECT 
    COLUMN_NAME,
    DATA_TYPE,
    CHARACTER_MAXIMUM_LENGTH
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'ROL'
  AND COLUMN_NAME = 'status';


SELECT * FROM dbo.ROL
SELECT * FROM dbo.ROL_OPCIONES
SELECT * FROM dbo.ROL_ROL_OPCIONES

DELETE FROM dbo.ROL WHERE id_rol = 2

SELECT * FROM dbo.ROL_USUARIOS

SELECT * FROM dbo.USUARIOS
SELECT * FROM dbo.PERSONA

SELECT definition
FROM sys.check_constraints
WHERE parent_object_id = OBJECT_ID('USUARIOS');
